version: "3.3"
services:
  app:
    user: "${UID}"
    build:
      context: ./app
    ports:
      - "0.0.0.0:5000:8000"
    networks:
      - docNet
    volumes:
      - "./app:/app"

networks:
  docNet:
    external: true
